# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30f95f8b322f93ea0315dab5b6b008ceae5c21b332a63e5000a7e0a2158ac1a927a10d7bb75c139a6048ce5f4e1449655d7329d3c204ec145377eabb2489edfd

test:
  secret_key_base: a3f321e0a6c2f8c9e1a154288ac5fcd08546e8e698fe6946c586cee0e08ea0c84c75a0753a718916af3d6f157abdef54970b043c109bd04d83ca9e8add2be596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
